whitelist_rules:
  - attributes
  - class_delegate_protocol
  - closing_brace
  - closure_end_indentation
  - closure_spacing
  - comma
  - compiler_protocol_init
  - control_statement
  - discarded_notification_center_observer
  - dynamic_inline
  - empty_count
  - empty_enum_arguments
  - empty_parameters
  - empty_parentheses_with_trailing_closure
  - explicit_init
  - fatal_error_message
  - file_length
  - first_where
  - for_where
  - force_cast
  - force_try
  - force_unwrapping
  - function_body_length
  - function_parameter_count
  - generic_type_name
  - identifier_name
  - implicit_getter
  - implicitly_unwrapped_optional
  - large_tuple
  - leading_whitespace
  - legacy_cggeometry_functions
  - legacy_constant
  - legacy_constructor
  - legacy_nsgeometry_functions
  - line_length
  - mark
  - multiline_arguments
  - multiline_parameters
  - nesting
  - no_extension_access_modifier
  - no_fallthrough_only
  - notification_center_detachment
  - number_separator
  - object_literal
  - operator_usage_whitespace
  - operator_whitespace
  - overridden_super_call
  - private_outlet
  - private_unit_test
  - prohibited_super_call
  - protocol_property_accessors_order
  - redundant_discardable_let
  - redundant_nil_coalescing
  - redundant_optional_initialization
  - redundant_string_enum_value
  - redundant_void_return
  - return_arrow_whitespace
  - shorthand_operator
  - sorted_imports
  - statement_position
  - switch_case_alignment
  - syntactic_sugar
  - trailing_comma
  - trailing_newline
  - trailing_semicolon
  - trailing_whitespace
  - type_body_length
  - type_name
  - unused_closure_parameter
  - unused_enumerated
  - unused_optional_binding
  - valid_ibinspectable
  - vertical_parameter_alignment
  - vertical_parameter_alignment_on_call
  - vertical_whitespace
  - void_return
  - weak_delegate

line_length:
  warning: 100
  error: 100
  ignores_urls: true

vertical_whitespace:
  max_empty_lines: 1
  severity: warning

identifier_name:
  min_length: 1

trailing_comma:
  multiline_comma: true
